language: node_js
node_js:
  - "12.16.1"
cache:
  npm: false
script: npm run build
deploy:
skip_cleanup: true
github_token: $GITHUB_TOKEN
local_dir: dist
on:
  branch: master
branches:
  only:
    - master
after_script:
  - cd dist
  - cd -